name: 'Creating Infra AWS with LocalStack'

on: [ push, pull_request ]

jobs:
  test:
    name: Pull a Cloud Pod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Start LocalStack
        run: |
          pip install pyopenssl -U
          docker pull localstack/localstack
          docker run --rm -d -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
          pip install localstack
          localstack start -d
          pip install awscli-local[ver1]
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

      - name: Login to LocalStack
        uses: LocalStack/localstack-github-actions-login@v0.1.0
        with:
          email: ${{ secrets.LOCALSTACK_USERNAME }}
          password: ${{ secrets.LOCALSTACK_PASSWORD }}