name: "CI from local infra with Localstack"

on:
  push:
    branches:
      - master

jobs:
  test:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: production

    permissions:
      id-token: write

    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0
        
      - name: "Run - Terraform Init"
        run: |
          cd terraform/
          terraform init -input=false

      - name: "Run - Terraform Apply"
        run: |
          cd terraform/
          terraform apply -auto-approve -input=false -no-color